# Section A: Data Structures & Control Structures
### 1) Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.


In [36]:
my_list=[28,12,23,25,44,46,98]
print(my_list)

[28, 12, 23, 25, 44, 46, 98]


In [37]:
# Append operation
my_list.append(50)
print(my_list)       # value add the end of list

[28, 12, 23, 25, 44, 46, 98, 50]


In [38]:
# Extend operation 
list=[1,2,3,4,5]
my_list.extend(list)  # add multiple items
print(my_list)

[28, 12, 23, 25, 44, 46, 98, 50, 1, 2, 3, 4, 5]


In [39]:
# Insert operation
my_list.insert(1,29)
print(my_list)  # add the value at specific position

[28, 29, 12, 23, 25, 44, 46, 98, 50, 1, 2, 3, 4, 5]


In [40]:
# remove operation
my_list.remove(98)
print(my_list)        # Removing values

[28, 29, 12, 23, 25, 44, 46, 50, 1, 2, 3, 4, 5]


In [31]:
# pop operation
my_list.pop()
print(my_list)  # Removing last value

[28, 29, 12, 23, 25, 44, 46, 50, 1, 2, 3, 4]


In [34]:
my_list.clear()
my_list   # removing all values in the list

[]

In [43]:
my_list

[28, 29, 12, 23, 25, 44, 46, 50, 1, 2, 3, 4, 5]

In [47]:
# index opeartion
print(my_list.index(44))   # Find the index number of specific values


5


In [49]:
# Count operation
print(my_list.count(44))  # count that how many times is occured

1


In [51]:
# Sort Function
my_list.sort()
my_list         # Arrange the data in ascending order

[1, 2, 3, 4, 5, 12, 23, 25, 28, 29, 44, 46, 50]

In [52]:
my_list.sort(reverse=True)
my_list                 # Arrange the data in descending order

[50, 46, 44, 29, 28, 25, 23, 12, 5, 4, 3, 2, 1]

## 2) Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [55]:
my_tuple=("Ram","Lakshman","Sita")
print(my_tuple)
print(type(my_tuple))

('Ram', 'Lakshman', 'Sita')
<class 'tuple'>


In [56]:
# changing name 
my_tuple[1]="Hanuman"

TypeError: 'tuple' object does not support item assignment

### Because tuple is immutable data type, it means it cannot change or modify the data. if we want to change the data then we want to convert that tuple into list and change it and after changing the name then convert it again in tuple.

## 3) Create a set of integers with some duplicate values. Print the set and explain the output.

In [57]:
my_set={1,2,2,3,4,5,5}
print(my_set)

{1, 2, 3, 4, 5}


### set cannot allows duplicate values. if the duplicate values is present in set then it cannot print that duplicate values, it print only non duplicate values

## 4) Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [59]:
my_dict={"name":"Yashwant","Age":23,"city":"Pune"}
print(my_dict)
print(type(my_dict))

{'name': 'Yashwant', 'Age': 23, 'city': 'Pune'}
<class 'dict'>


In [62]:
# upadting the age
my_dict["Age"]=21

In [63]:
my_dict  # Sucessfully update the dictionary

{'name': 'Yashwant', 'Age': 21, 'city': 'Pune'}

In [64]:
# updating the key with email
my_dict["email"]="abc@gmail.com"
print(my_dict)   # Successfully updating the key with email

{'name': 'Yashwant', 'Age': 21, 'city': 'Pune', 'email': 'abc@gmail.com'}


In [65]:
print(my_dict.keys())

dict_keys(['name', 'Age', 'city', 'email'])


In [66]:
print(my_dict.values())

dict_values(['Yashwant', 21, 'Pune', 'abc@gmail.com'])


## 5) Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [71]:
age=int(input("enter your age"))
if age>=18:
    print("The person is eligible for vote")
else:
    print("The person is not eligible for vote")

enter your age 19


The person is eligible for vote


### 6) Given a 'marks' variable, print the grade:
### - 90 and above: 'A'
### - 75–89: 'B'
### - 50–74: 'C'
### - Below 50: 'Fail'


In [81]:
# We use elif conditional statement for checking multiple condition

marks=int(input("enter your marks"))
if marks>=90 and marks<=100:
    print("A Grade")
elif marks>=75 and marks<=89:
    print("B Grade")
elif marks>=50 and marks<=74:
    print("C Grade")
else:
    print("fail")

enter your marks 75


B Grade


## 7) Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [89]:
num=int(input("Enter your number"))
if num==0:
    print("The number is Zero")
if num>0:
    print("The Number is Positive")
if num<0:
    print("The number is Negative")

Enter your number -21


The number is Negative


# Section B: Numpy

### 8) Create:
### - A scalar using np.array(5)
### - A 1D array with values 1 to 5
### - A 2D array (2x3) with values from 10 to 60 in steps of 10


In [4]:
import numpy as np

# A scalar using np.array(5)
scaler=np.array(5)

# A 1D array with values 1 to 5
one_d_array=np.array([1,2,3,4,5])

# A 2D array (2x3) with values from 10 to 60 in steps of 10
two_d_array=np.array([[10,20,30],
                     [40,50,60]])

print(scaler)
print(one_d_array)
print(two_d_array)

5
[1 2 3 4 5]
[[10 20 30]
 [40 50 60]]


## 9) Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [12]:
import random

array=np.random.randint(0,101, size=(4,4))
print(array)

[[ 37  84  65  22]
 [100  36  92  57]
 [ 26  26  24  61]
 [ 83  95  60  84]]


### 10) Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'

In [14]:
import pandas as np
import numpy as np

In [15]:
#create a 3*3 numpy array
array=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
# convert it into pandas dataframe and add columns
df=pd.DataFrame(array, columns=['A','B','C'])
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


# Section C: Exploring Pandas


### 11) Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
### - Use .info(), .describe()
### - Select 'Name' and 'City' columns
### - Drop 'City' column
### - Fill any missing values in 'Salary' column with the mean
### - Remove any duplicate rows


In [19]:
import pandas as pd

In [51]:
# Manuallly Creating data
data={
    'name': ['Rahul','Rohit','Yashwant','Tushar','Ishwari','Vaishnavi','Pallavi','Bhagyashree','Snehal','Sanika',],
    'age': [23,20,19,25,30,36,29,22,36,40],
    'city': ['Mumbai','Pune','Nashik','Satana','Solapur','Pune','Mumbai','Nashik','Pune','Delhi'],
    'Salary': [25000,30000,15000,40000,35000,33000,41000,50000,66000,36000]
}

print(data)

{'name': ['Rahul', 'Rohit', 'Yashwant', 'Tushar', 'Ishwari', 'Vaishnavi', 'Pallavi', 'Bhagyashree', 'Snehal', 'Sanika'], 'age': [23, 20, 19, 25, 30, 36, 29, 22, 36, 40], 'city': ['Mumbai', 'Pune', 'Nashik', 'Satana', 'Solapur', 'Pune', 'Mumbai', 'Nashik', 'Pune', 'Delhi'], 'Salary': [25000, 30000, 15000, 40000, 35000, 33000, 41000, 50000, 66000, 36000]}


In [52]:
# convrting data into Dataframe
df=pd.DataFrame(data)

In [53]:
df

,name,age,city,Salary
0,Rahul,23,Mumbai,25000
1,Rohit,20,Pune,30000
2,Yashwant,19,Nashik,15000
3,Tushar,25,Satana,40000
4,Ishwari,30,Solapur,35000
5,Vaishnavi,36,Pune,33000
6,Pallavi,29,Mumbai,41000
7,Bhagyashree,22,Nashik,50000
8,Snehal,36,Pune,66000
9,Sanika,40,Delhi,36000


In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    10 non-null     object
 1   age     10 non-null     int64 
 2   city    10 non-null     object
 3   Salary  10 non-null     int64 
dtypes: int64(2), object(2)
memory usage: 448.0+ bytes


In [55]:
df.describe()

,age,Salary
count,10.000000,10.0000
mean,28.000000,37100.0000
std,7.393691,13876.0385
min,19.000000,15000.0000
25%,22.250000,30750.0000
50%,27.000000,35500.0000
75%,34.500000,40750.0000
max,40.000000,66000.0000


In [56]:
df.isnull().sum()

name      0
age       0
city      0
Salary    0
dtype: int64

In [57]:
df.shape

(10, 4)

In [58]:
df.duplicated().sum()

np.int64(0)

In [59]:
df[['name','city']]

,name,city
0,Rahul,Mumbai
1,Rohit,Pune
2,Yashwant,Nashik
3,Tushar,Satana
4,Ishwari,Solapur
5,Vaishnavi,Pune
6,Pallavi,Mumbai
7,Bhagyashree,Nashik
8,Snehal,Pune
9,Sanika,Delhi


In [60]:
mean_salary=df['Salary'].mean()

In [61]:
mean_salary

np.float64(37100.0)

In [64]:
new_df=df.drop('city',axis=1)

In [65]:
new_df

,name,age,Salary
0,Rahul,23,25000
1,Rohit,20,30000
2,Yashwant,19,15000
3,Tushar,25,40000
4,Ishwari,30,35000
5,Vaishnavi,36,33000
6,Pallavi,29,41000
7,Bhagyashree,22,50000
8,Snehal,36,66000
9,Sanika,40,36000
